apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "olamundo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "olamundo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "olamundo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "olamundo.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
