apiVersion: v1
kind: Service
metadata:
  name: {{ include "olamundo.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "olamundo.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
